# Generated by Django 3.2.19 on 2023-05-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0002_auto_20230517_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='case_content',
            field=models.CharField(default='Case', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='cpu_cooler_content',
            field=models.CharField(default='CPU-Cooler', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='fans_content',
            field=models.CharField(default='Fans', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='motherboard_content',
            field=models.CharField(default='Motherboard', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='psu_content',
            field=models.CharField(default='PSU', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='ram_content',
            field=models.CharField(default='RAM', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='storage_content',
            field=models.CharField(default='Storage', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='cpu_content',
            field=models.CharField(default='CPU', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='gpu_content',
            field=models.CharField(default='GPU', max_length=150),
        ),
    ]
