# Generated by Django 3.2.19 on 2023-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0004_auto_20230526_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='case_content',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cpu_content',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cpu_cooler_content',
            new_name='cpu_cooler',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fans_content',
            new_name='fans',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='gpu_content',
            new_name='gpu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='motherboard_content',
            new_name='motherboard',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='psu_content',
            new_name='psu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ram_content',
            new_name='ram',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='storage_content',
            new_name='storage',
        ),
        migrations.AddField(
            model_name='post',
            name='cpu_manufacturer',
            field=models.CharField(default='Intel', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='gpu_manufacturer',
            field=models.CharField(default='Nvidia', max_length=100),
        ),
    ]
