# Generated by Django 3.2.19 on 2023-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0006_auto_20230606_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuManufacturerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_manufacturer', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GpuManufacturerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_manufacturer', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='ManufacturerOptions',
        ),
    ]
