# Generated by Django 3.2.19 on 2023-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0007_auto_20230606_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cpu_manufacturer',
            field=models.CharField(default='Intel', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='gpu_manufacturer',
            field=models.CharField(default='Nvidia', max_length=100),
        ),
    ]
