# Generated by Django 3.2.19 on 2023-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0008_auto_20230606_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cpu_manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='gpu_manufacturer',
            field=models.CharField(max_length=100),
        ),
    ]
